name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ yirameon }}
          TIMEZONE: Asia/Seoul
